spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:postgresql://localhost:5433/dbtest
    username: usertest
    password: pwtest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
config:
  employee:
    message: Hello123 World
